[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sigritto = "FvQihDMQ3Y55X3ZV1oowcm5CM2iwgioEiyV54KfXPWks"

[programs.testnet]
sigritto = "FvQihDMQ3Y55X3ZV1oowcm5CM2iwgioEiyV54KfXPWks"

[programs.devnet]
sigritto = "FvQihDMQ3Y55X3ZV1oowcm5CM2iwgioEiyV54KfXPWks"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
